/* eslint-disable */
// Generated by Fieldstone. Do not edit.
import '@fieldstone/core';

declare module '@fieldstone/core' {
  interface GeneratedCollections {
  "pages": {
    id: string;
    "headline": string;
    "path": string;
    "summary"?: string;
    createdAt: Date;
    updatedAt: Date;
  };
  "posts": {
    id: string;
    "title": string;
    "description": string;
    createdAt: Date;
    updatedAt: Date;
  };
  }
}
