import type { FieldstoneConfig } from '../types.ts';
import { toUniqueIdentifier } from './identifiers.ts';
import { validateFieldstoneConfig } from './validation.ts';

export function generateDrizzleSchemaSource(config: FieldstoneConfig) {
	validateFieldstoneConfig(config);

	const collectionIdentifiers = new Set<string>();
	const tableDeclarations = Object.values(config.collections)
		.map((collection) => {
			const fieldIdentifiers = new Set<string>();
			const fields = collection.fields
				.map((field) => {
					const identifier = toUniqueIdentifier(field.name, fieldIdentifiers);
					const column = `text(${JSON.stringify(field.name)})${field.required ? '.notNull()' : ''}`;
					return `\t${identifier}: ${column},`;
				})
				.join('\n');
			const collectionIdentifier = toUniqueIdentifier(
				collection.slug,
				collectionIdentifiers,
				'collection_'
			);

			return `export const ${collectionIdentifier} = sqliteTable(${JSON.stringify(collection.slug)}, {
\tid: text('id')
\t\t.primaryKey()
\t\t.$defaultFn(() => crypto.randomUUID()),
${fields}
\tcreatedAt: integer('created_at', { mode: 'timestamp' })
\t\t.notNull()
\t\t.$defaultFn(() => new Date()),
\tupdatedAt: integer('updated_at', { mode: 'timestamp' })
\t\t.notNull()
\t\t.$defaultFn(() => new Date())
});`;
		})
		.join('\n\n');

	return `// Generated by Fieldstone. Do not edit.
import crypto from 'node:crypto';
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

${tableDeclarations}
`;
}
