import type { CollectionModel, CompiledSystemField } from './collection-model.ts';

function renderSystemColumn(field: CompiledSystemField) {
	if (field.identifier === 'id') {
		return `\t${field.identifier}: text(${JSON.stringify(field.columnName)})
\t\t.primaryKey()
\t\t.$defaultFn(() => crypto.randomUUID()),`;
	}

	return `\t${field.identifier}: integer(${JSON.stringify(field.columnName)}, { mode: 'timestamp' })
\t\t.notNull()
\t\t.$defaultFn(() => new Date())${field.identifier === 'createdAt' ? ',' : ''}`;
}

export function createDrizzleSchemaSource(model: CollectionModel) {
	const tableDeclarations = model.collections
		.map((collection) => {
			const fields = collection.fields
				.map((field) => {
					const column = `text(${JSON.stringify(field.name)})${field.required ? '.notNull()' : ''}`;
					return `\t${field.identifier}: ${column},`;
				})
				.join('\n');
			const [idColumn, ...timestampColumns] = collection.systemFields.map(renderSystemColumn);

			return `export const ${collection.tableIdentifier} = sqliteTable(${JSON.stringify(collection.slug)}, {
${idColumn}
${fields}
${timestampColumns.join('\n')}
});`;
		})
		.join('\n\n');

	return `// Generated by Fieldstone. Do not edit.
import crypto from 'node:crypto';
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

${tableDeclarations}
`;
}
