import type { SchemaPlan } from './schema-plan.ts';

function sourceString(value: string) {
	return `'${value.replace(/'/g, "\\'")}'`;
}

export function createDrizzleSchemaSource(plan: SchemaPlan) {
	const { createdAt, id, updatedAt } = plan.systemFields;
	const tableDeclarations = plan.collections
		.map((collection) => {
			const fields = collection.fields
				.map((field) => {
					const column = `text(${JSON.stringify(field.name)})${field.required ? '.notNull()' : ''}`;
					return `\t${field.sourceIdentifier}: ${column},`;
				})
				.join('\n');

			return `export const ${collection.sourceIdentifier} = sqliteTable(${JSON.stringify(collection.slug)}, {
\t${id.name}: text(${sourceString(id.columnName)})
\t\t.primaryKey()
\t\t.$defaultFn(() => crypto.randomUUID()),
${fields}
\t${createdAt.name}: integer(${sourceString(createdAt.columnName)}, { mode: 'timestamp' })
\t\t.notNull()
\t\t.$defaultFn(() => new Date()),
\t${updatedAt.name}: integer(${sourceString(updatedAt.columnName)}, { mode: 'timestamp' })
\t\t.notNull()
\t\t.$defaultFn(() => new Date())
});`;
		})
		.join('\n\n');

	return `// Generated by Fieldstone. Do not edit.
import crypto from 'node:crypto';
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

${tableDeclarations}
`;
}
