import type { SchemaPlan } from './schema-plan.ts';

export function createTypesDeclaration(plan: SchemaPlan) {
	const { createdAt, id, updatedAt } = plan.systemFields;
	const collections = plan.collections
		.map((collection) => {
			const fields = collection.fields
				.map((field) => `    ${JSON.stringify(field.name)}${field.required ? '' : '?'}: string;`)
				.join('\n');

			return `  ${JSON.stringify(collection.slug)}: {\n    ${id.name}: string;\n${fields}\n    ${createdAt.name}: Date;\n    ${updatedAt.name}: Date;\n  };`;
		})
		.join('\n');

	return `/* eslint-disable */\n// Generated by Fieldstone. Do not edit.\nimport '@fieldstone/core';\n\ndeclare module '@fieldstone/core' {\n  interface GeneratedCollections {\n${collections}\n  }\n}\n`;
}
