import type { CollectionModel } from './collection-model.ts';

export function createTypesDeclaration(model: CollectionModel) {
	const collections = model.collections
		.map((collection) => {
			const fields = collection.fields
				.map((field) => `    ${JSON.stringify(field.name)}${field.required ? '' : '?'}: string;`)
				.join('\n');
			const [id, createdAt, updatedAt] = collection.systemFields;

			return `  ${JSON.stringify(collection.slug)}: {\n    ${id.identifier}: string;\n${fields}\n    ${createdAt.identifier}: Date;\n    ${updatedAt.identifier}: Date;\n  };`;
		})
		.join('\n');

	return `/* eslint-disable */\n// Generated by Fieldstone. Do not edit.\nimport '@fieldstone/core';\n\ndeclare module '@fieldstone/core' {\n  interface GeneratedCollections {\n${collections}\n  }\n}\n`;
}
