import type { SchemaPlan } from './collection-model.ts';

function renderTypeColumn(column: SchemaPlan['collections'][number]['columns'][number]) {
	const name = column.origin === 'system' ? column.identifier : JSON.stringify(column.name);
	const type =
		column.origin === 'field' && !column.required
			? `${column.typeScriptType} | null`
			: column.typeScriptType;
	return `    ${name}: ${type};`;
}

export function createTypesDeclaration(schemaPlan: SchemaPlan) {
	const collections = schemaPlan.collections
		.map((collection) => {
			const fields = collection.columns.map(renderTypeColumn).join('\n');

			return `  ${JSON.stringify(collection.slug)}: {\n${fields}\n  };`;
		})
		.join('\n');

	return `/* eslint-disable */\n// Generated by Fieldstone. Do not edit.\nimport '@fieldstone/core';\n\ndeclare module '@fieldstone/core' {\n  interface GeneratedCollections {\n${collections}\n  }\n}\n`;
}
