import crypto from 'node:crypto';

import { integer, sqliteTable, text as sqliteText } from 'drizzle-orm/sqlite-core';

import type { FieldstoneConfig } from './types.ts';

const reservedFieldNames = new Set([
	'__proto__',
	'id',
	'createdAt',
	'updatedAt',
	'created_at',
	'updated_at'
]);

function toIdentifier(value: string) {
	const identifier = value
		.replace(/[^a-zA-Z0-9_$]+/g, '_')
		.replace(/^[^a-zA-Z_$]+/, '_')
		.replace(/_+/g, '_')
		.replace(/^_+|_+$/g, '');

	return identifier || 'collection';
}

function toUniqueIdentifier(value: string, used: Set<string>, prefix = '') {
	const base = toIdentifier(`${prefix}${value}`);
	let identifier = base;
	let index = 2;

	while (used.has(identifier)) {
		identifier = `${base}_${index}`;
		index += 1;
	}

	used.add(identifier);
	return identifier;
}

function validateCollectionSlugs(config: FieldstoneConfig) {
	const seen = new Set<string>();

	for (const collection of Object.values(config.collections)) {
		if (collection.slug === '__proto__') {
			throw new Error('Reserved collection slug: __proto__');
		}

		const normalizedSlug = collection.slug.toLowerCase();
		if (seen.has(normalizedSlug)) throw new Error(`Duplicate collection slug: ${collection.slug}`);
		seen.add(normalizedSlug);
	}
}

export function validateCollectionFields(
	collectionFields: readonly FieldstoneConfig['collections'][string]['fields'][number][]
) {
	const seen = new Set<string>();

	for (const field of collectionFields) {
		if (reservedFieldNames.has(field.name)) throw new Error(`Reserved field name: ${field.name}`);
		const normalizedName = field.name.toLowerCase();
		if (seen.has(normalizedName)) throw new Error(`Duplicate field name: ${field.name}`);
		seen.add(normalizedName);
	}
}

function validateFieldstoneConfig(config: FieldstoneConfig) {
	validateCollectionSlugs(config);
	for (const collection of Object.values(config.collections)) {
		validateCollectionFields(collection.fields);
	}
}

export function compileFieldstoneConfig(config: FieldstoneConfig) {
	validateFieldstoneConfig(config);
	const tables: Record<string, any> = {};

	for (const collection of Object.values(config.collections)) {
		const columns: Record<string, any> = {};

		for (const field of collection.fields) {
			columns[field.name] = field.required
				? sqliteText(field.name).notNull()
				: sqliteText(field.name);
		}

		tables[collection.slug] = sqliteTable(collection.slug, {
			id: sqliteText('id')
				.primaryKey()
				.$defaultFn(() => crypto.randomUUID()),
			...columns,
			createdAt: integer('created_at', { mode: 'timestamp' })
				.notNull()
				.$defaultFn(() => new Date()),
			updatedAt: integer('updated_at', { mode: 'timestamp' })
				.notNull()
				.$defaultFn(() => new Date())
		});
	}

	return {
		schema: tables,
		tables
	};
}

export function createSchemaFingerprint(config: FieldstoneConfig) {
	validateFieldstoneConfig(config);

	return JSON.stringify(
		Object.values(config.collections)
			.map((collection) => ({
				fields: collection.fields.map((field) => ({
					name: field.name,
					multiline: Boolean(field.multiline),
					required: Boolean(field.required),
					type: field.type
				})),
				slug: collection.slug
			}))
			.sort((a, b) => a.slug.localeCompare(b.slug))
	);
}

export function generateTypes(config: FieldstoneConfig) {
	validateFieldstoneConfig(config);

	const collections = Object.values(config.collections)
		.map((collection) => {
			const fields = collection.fields
				.map((field) => `    ${JSON.stringify(field.name)}${field.required ? '' : '?'}: string;`)
				.join('\n');

			return `  ${JSON.stringify(collection.slug)}: {\n    id: string;\n${fields}\n    createdAt: Date;\n    updatedAt: Date;\n  };`;
		})
		.join('\n');

	return `/* eslint-disable */\n// Generated by Fieldstone. Do not edit.\nimport '@fieldstone/core';\n\ndeclare module '@fieldstone/core' {\n  interface GeneratedCollections {\n${collections}\n  }\n}\n`;
}

export function generateDrizzleSchemaSource(config: FieldstoneConfig) {
	validateFieldstoneConfig(config);

	const collectionIdentifiers = new Set<string>();
	const tableDeclarations = Object.values(config.collections)
		.map((collection) => {
			const fieldIdentifiers = new Set<string>();
			const fields = collection.fields
				.map((field) => {
					const identifier = toUniqueIdentifier(field.name, fieldIdentifiers);
					const column = `text(${JSON.stringify(field.name)})${field.required ? '.notNull()' : ''}`;
					return `\t${identifier}: ${column},`;
				})
				.join('\n');
			const collectionIdentifier = toUniqueIdentifier(
				collection.slug,
				collectionIdentifiers,
				'collection_'
			);

			return `export const ${collectionIdentifier} = sqliteTable(${JSON.stringify(collection.slug)}, {
\tid: text('id')
\t\t.primaryKey()
\t\t.$defaultFn(() => crypto.randomUUID()),
${fields}
\tcreatedAt: integer('created_at', { mode: 'timestamp' })
\t\t.notNull()
\t\t.$defaultFn(() => new Date()),
\tupdatedAt: integer('updated_at', { mode: 'timestamp' })
\t\t.notNull()
\t\t.$defaultFn(() => new Date())
});`;
		})
		.join('\n\n');

	return `// Generated by Fieldstone. Do not edit.
import crypto from 'node:crypto';
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

${tableDeclarations}
`;
}
