import type { SchemaPlan } from "./collection-model.js";
import { renderColumnSource } from "./column-renderers.js";

export function createDrizzleSchemaSource(schemaPlan: SchemaPlan) {
  const tableDeclarations = [...schemaPlan.collections, ...schemaPlan.globals]
    .map((collection) => {
      return `export const ${collection.tableIdentifier} = sqliteTable(${JSON.stringify(collection.slug)}, {
${collection.columns.map(renderColumnSource).join("\n")}
});`;
    })
    .join("\n\n");

  return `// Generated by Fieldstone. Do not edit.
import crypto from 'node:crypto';
import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

${tableDeclarations}
`;
}
