import type { CompiledColumn, SchemaPlan } from "./collection-model.ts";

function renderColumn(column: CompiledColumn) {
  if (column.sourceExpression === "text") {
    const renderedColumn = `text(${JSON.stringify(column.columnName)})${column.required ? ".notNull()" : ""}`;
    return `\t${column.identifier}: ${renderedColumn},`;
  }

  if (column.sourceExpression === "boolean") {
    return `\t${column.identifier}: integer(${JSON.stringify(column.columnName)}, { mode: 'boolean' }).notNull().default(false),`;
  }

  if (column.sourceExpression === "uuidTextPrimaryKey") {
    return `\t${column.identifier}: text(${JSON.stringify(column.columnName)})
\t\t.primaryKey()
\t\t.$defaultFn(() => crypto.randomUUID()),`;
  }

  return `\t${column.identifier}: integer(${JSON.stringify(column.columnName)}, { mode: 'timestamp' })
\t\t.notNull()
\t\t.$defaultFn(() => new Date())${column.identifier === "createdAt" ? "," : ""}`;
}

export function createDrizzleSchemaSource(schemaPlan: SchemaPlan) {
  const tableDeclarations = [...schemaPlan.collections, ...schemaPlan.globals]
    .map((collection) => {
      return `export const ${collection.tableIdentifier} = sqliteTable(${JSON.stringify(collection.slug)}, {
${collection.columns.map(renderColumn).join("\n")}
});`;
    })
    .join("\n\n");

  return `// Generated by Fieldstone. Do not edit.
import crypto from 'node:crypto';
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

${tableDeclarations}
`;
}
