import type { CompiledContent, SchemaPlan } from "./collection-model.ts";

function renderTypeColumn(column: CompiledContent["columns"][number]) {
  const type =
    column.origin === "field" && !column.required
      ? `${column.typeScriptType} | null`
      : column.typeScriptType;
  // The injected draft status column has a runtime default, so it's optional on
  // create/update even though the stored value is always non-null. Mark it
  // optional (not nullable) so mutation input types don't demand it. ("_status"
  // is STATUS_FIELD_NAME from @fieldstone/schema; collections can't define it.)
  const optional = column.name === "_status";
  return `    ${column.typeScriptProperty}${optional ? "?" : ""}: ${type};`;
}

function renderGeneratedEntries(contents: readonly CompiledContent[]) {
  return contents
    .map((content) => {
      const fields = content.columns.map(renderTypeColumn).join("\n");

      return `  ${JSON.stringify(content.slug)}: {\n${fields}\n  };`;
    })
    .join("\n");
}

export function createTypesDeclaration(schemaPlan: SchemaPlan) {
  const collections = renderGeneratedEntries(schemaPlan.collections);
  const globals = renderGeneratedEntries(schemaPlan.globals);

  return `/* eslint-disable */\n// Generated by Fieldstone. Do not edit.\nimport '@fieldstone/schema';\n\ndeclare module '@fieldstone/schema' {\n  interface GeneratedCollections {\n${collections}\n  }\n\n  interface GeneratedGlobals {\n${globals}\n  }\n}\n`;
}
