import type { CompiledContent, SchemaPlan } from "./collection-model.js";

function renderTypeColumn(column: CompiledContent["columns"][number]) {
  // optionalInput fields (defaulted fields, optional arrays) are optional on
  // create/update but non-null when stored, so mark them `?` rather than nullable.
  const type =
    column.origin === "field" && !column.required && !column.optionalInput
      ? `${column.typeScriptType} | null`
      : column.typeScriptType;
  return `    ${column.typeScriptProperty}${column.optionalInput ? "?" : ""}: ${type};`;
}

function renderGeneratedEntries(contents: readonly CompiledContent[]) {
  return contents
    .map((content) => {
      const fields = content.columns.map(renderTypeColumn).join("\n");

      return `  ${JSON.stringify(content.slug)}: {\n${fields}\n  };`;
    })
    .join("\n");
}

// Per-collection map of relation/upload field name → { target slug, hasMany },
// consumed by PopulatedDocument<T> to type `depth`-populated reads. Top-level
// relation fields only (group/array-nested relations are not yet populated).
function renderRelationEntries(contents: readonly CompiledContent[]) {
  return contents
    .flatMap((content) => {
      const relations = content.fields
        .filter((field) => field.type === "relationship" || field.type === "upload")
        .map(
          (field) =>
            `    ${JSON.stringify(field.name)}: { to: ${JSON.stringify(
              field.relationTo,
            )}; many: ${Boolean(field.hasMany)} };`,
        )
        .join("\n");

      return relations ? [`  ${JSON.stringify(content.slug)}: {\n${relations}\n  };`] : [];
    })
    .join("\n");
}

export function createTypesDeclaration(schemaPlan: SchemaPlan) {
  const collections = renderGeneratedEntries(schemaPlan.collections);
  const globals = renderGeneratedEntries(schemaPlan.globals);
  const relations = renderRelationEntries(schemaPlan.collections);

  return `/* eslint-disable */\n// Generated by Fieldstone. Do not edit.\nimport '@hugo-hsi-dev/schema';\n\ndeclare module '@hugo-hsi-dev/schema' {\n  interface GeneratedCollections {\n${collections}\n  }\n\n  interface GeneratedGlobals {\n${globals}\n  }\n\n  interface GeneratedCollectionRelations {\n${relations}\n  }\n}\n`;
}
