import type { CompiledContent, SchemaPlan } from "./collection-model.ts";

function renderTypeColumn(column: CompiledContent["columns"][number]) {
  const type =
    column.origin === "field" && !column.required
      ? `${column.typeScriptType} | null`
      : column.typeScriptType;
  return `    ${column.typeScriptProperty}: ${type};`;
}

function renderGeneratedEntries(contents: readonly CompiledContent[]) {
  return contents
    .map((content) => {
      const fields = content.columns.map(renderTypeColumn).join("\n");

      return `  ${JSON.stringify(content.slug)}: {\n${fields}\n  };`;
    })
    .join("\n");
}

export function createTypesDeclaration(schemaPlan: SchemaPlan) {
  const collections = renderGeneratedEntries(schemaPlan.collections);
  const globals = renderGeneratedEntries(schemaPlan.globals);

  return `/* eslint-disable */\n// Generated by Fieldstone. Do not edit.\nimport '@fieldstone/schema';\n\ndeclare module '@fieldstone/schema' {\n  interface GeneratedCollections {\n${collections}\n  }\n\n  interface GeneratedGlobals {\n${globals}\n  }\n}\n`;
}
