import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { FIELDSTONE_ADMIN_REMOTE_NAMES } from "@hugo-hsi-dev/schema";

// SvelteKit registers remote functions by their file path inside the app, so the
// barrel must live in the route tree (not in the generated `.fieldstone/` dir). This
// path is a fixed convention that `fieldstone init` scaffolds and `generate` refreshes.
export const ADMIN_REMOTES_BARREL_PATH = "src/routes/admin/dashboard.remote.ts";

export function renderAdminRemotesBarrel(): string {
  const names = [...FIELDSTONE_ADMIN_REMOTE_NAMES].sort();
  const reexports = names.map((name) => `\t${name}`).join(",\n");
  return `// GENERATED by Fieldstone — do not edit. Run \`fieldstone generate\` to update.
import config from '$fieldstone-config';
import { createFieldstoneAdminRemotes } from '@hugo-hsi-dev/remotes';

export const {
${reexports}
} = createFieldstoneAdminRemotes({ config });
`;
}

export async function writeAdminRemotesBarrel(root: string): Promise<void> {
  const file = path.join(root, ADMIN_REMOTES_BARREL_PATH);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, renderAdminRemotesBarrel());
}
