import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

// SvelteKit registers remote functions by their file path inside the app, so the
// barrel must live in the route tree (not in the generated `.fieldstone/` dir). This
// path is a fixed convention that `fieldstone init` scaffolds and `generate` refreshes.
export const ADMIN_REMOTES_BARREL_PATH = "src/routes/admin/dashboard.remote.ts";

const ADMIN_REMOTE_NAMES = [
  "createDocument",
  "deleteDocument",
  "getCollection",
  "getDocument",
  "getGlobal",
  "getGlobalConfig",
  "listCollections",
  "listDocuments",
  "listGlobals",
  "listRelationOptions",
  "updateDocument",
  "updateGlobal",
  "uploadMedia",
];

export function renderAdminRemotesBarrel(): string {
  const reexports = ADMIN_REMOTE_NAMES.map((name) => `\t${name}`).join(",\n");
  return `// GENERATED by Fieldstone — do not edit. Run \`fieldstone generate\` to update.
import { resolve } from '$app/paths';
import { form, getRequestEvent, query } from '$app/server';
import { error, invalid, redirect } from '@sveltejs/kit';
import config from '$fieldstone-config';
import { createFieldstoneAdminRemotes } from '@hugo-hsi-dev/admin-runtime/sveltekit';

export const {
${reexports}
} = createFieldstoneAdminRemotes({
\tconfig,
\tkit: { error, form, getRequestEvent, invalid, query, redirect, resolve }
});
`;
}

export async function writeAdminRemotesBarrel(root: string): Promise<void> {
  const file = path.join(root, ADMIN_REMOTES_BARREL_PATH);
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, renderAdminRemotesBarrel());
}
