import crypto from 'node:crypto';

import { integer, sqliteTable, text as sqliteText } from 'drizzle-orm/sqlite-core';

import type { FieldstoneConfig } from './types.ts';

export function compileFieldstoneConfig(config: FieldstoneConfig) {
	const tables: Record<string, any> = {};

	for (const collection of Object.values(config.collections)) {
		const columns: Record<string, any> = {};

		for (const field of collection.fields) {
			columns[field.name] = field.required
				? sqliteText(field.name).notNull()
				: sqliteText(field.name);
		}

		tables[collection.slug] = sqliteTable(collection.slug, {
			id: sqliteText('id')
				.primaryKey()
				.$defaultFn(() => crypto.randomUUID()),
			...columns,
			createdAt: integer('created_at', { mode: 'timestamp' })
				.notNull()
				.$defaultFn(() => new Date()),
			updatedAt: integer('updated_at', { mode: 'timestamp' })
				.notNull()
				.$defaultFn(() => new Date())
		});
	}

	return {
		schema: tables,
		tables
	};
}

export function createSchemaFingerprint(config: FieldstoneConfig) {
	return JSON.stringify(
		Object.values(config.collections)
			.map((collection) => ({
				fields: collection.fields.map((field) => ({
					name: field.name,
					multiline: Boolean(field.multiline),
					required: Boolean(field.required),
					type: field.type
				})),
				slug: collection.slug
			}))
			.sort((a, b) => a.slug.localeCompare(b.slug))
	);
}

export function generateTypes(config: FieldstoneConfig) {
	const collections = Object.values(config.collections)
		.map((collection) => {
			const fields = collection.fields
				.map((field) => `    ${JSON.stringify(field.name)}: string;`)
				.join('\n');

			return `  ${JSON.stringify(collection.slug)}: {\n    id: string;\n${fields}\n    createdAt: Date;\n    updatedAt: Date;\n  };`;
		})
		.join('\n');

	return `/* eslint-disable */\n// Generated by Fieldstone. Do not edit.\ndeclare namespace Fieldstone {\n  interface GeneratedCollections {\n${collections}\n  }\n}\n`;
}
