// GENERATED by Fieldstone — do not edit. Run `fieldstone generate` to update.
import config from '$fieldstone-config';
import { createFieldstoneAdminRemotes } from '@hugo-hsi-dev/remotes';

export const {
	createDocument,
	deleteDocument,
	getCollection,
	getDocument,
	getGlobal,
	getGlobalConfig,
	listCollections,
	listDocuments,
	listGlobals,
	listRelationOptions,
	updateDocument,
	updateGlobal,
	uploadMedia
} = createFieldstoneAdminRemotes({ config });
