// Generated by Fieldstone. Do not edit.
import crypto from 'node:crypto';
import { integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const collection_empty = sqliteTable("empty", {
	id: text("id")
		.primaryKey()
		.$defaultFn(() => crypto.randomUUID()),
	createdAt: integer("created_at", { mode: 'timestamp' })
		.notNull()
		.$defaultFn(() => new Date()),
	updatedAt: integer("updated_at", { mode: 'timestamp' })
		.notNull()
		.$defaultFn(() => new Date())
});

export const collection_pages = sqliteTable("pages", {
	id: text("id")
		.primaryKey()
		.$defaultFn(() => crypto.randomUUID()),
	headline: text("headline").notNull(),
	path: text("path").notNull(),
	summary: text("summary"),
	createdAt: integer("created_at", { mode: 'timestamp' })
		.notNull()
		.$defaultFn(() => new Date()),
	updatedAt: integer("updated_at", { mode: 'timestamp' })
		.notNull()
		.$defaultFn(() => new Date())
});

export const collection_posts = sqliteTable("posts", {
	id: text("id")
		.primaryKey()
		.$defaultFn(() => crypto.randomUUID()),
	title: text("title").notNull(),
	description: text("description").notNull(),
	createdAt: integer("created_at", { mode: 'timestamp' })
		.notNull()
		.$defaultFn(() => new Date()),
	updatedAt: integer("updated_at", { mode: 'timestamp' })
		.notNull()
		.$defaultFn(() => new Date())
});
