/* eslint-disable */
// Generated by Fieldstone. Do not edit.
import '@fieldstone/schema';

declare module '@fieldstone/schema' {
  interface GeneratedCollections {
  "empty": {
    id: string;
    createdAt: Date;
    updatedAt: Date;
  };
  "pages": {
    id: string;
    "headline": string;
    "path": string;
    "summary": string | null;
    createdAt: Date;
    updatedAt: Date;
  };
  "posts": {
    id: string;
    "title": string;
    "description": string;
    createdAt: Date;
    updatedAt: Date;
  };
  }
}
